### ISSUE TITLE
Never dropping the package build number.

### ISSUE THREAD

**Issue by rainwoodman** [bccp/conda-channel-bccp#13]
I think we shall not drop the package build number.
Because travis may have already built a newer version with the higher build number before we drop it when a new version is release. As an example, we see a bunch of 0.2.6 version of nbodykit -- the `_3` ones all contained bad dependency, but the fixed version is only in _1 and _2; so they are never installed..

**Comment by nickhand** [comment]
By drop you mean decrease? This seems reasonable given our automatic pypi versioning code. It is sorted out now?

**Comment by rainwoodman** [comment]
Yes I mean decrease. I suppose it is fixed now, but haven't tested on a clean install yet.

**Comment by nickhand** [comment]
I was still getting build 2 for v0.2.6 of nbodykit...I've just manually deleted the older build versions for v0.2.6, leaving only build 3. This appears to have fixed the issue I was having
